### ISSUE TITLE
Populate Book Combo Box

### ISSUE THREAD

**Issue by crex424** [crex424/LibraryBookRegistration#11]
- [x] Populate ComboBox with a list of book data.

Pre-requisites:
- [x] #36

**Comment by crex424** [comment]
Accidently made changes and pushed in master instead of a branch. Oops. @TungKimProgrammer let me know if there are any issues that arise from my mistake.

**Comment by crex424** [comment]
Accidently pushed changes to master branch, So far things have worked so I will close this issue. If any problems come up, please open a new issue.

**Comment by TungKimProgrammer** [comment]
Refactor PopulateBookComboBox to make it responsive to Customer ComboBox selected index changed and display books not yet registered by Customer ID

**Comment by TungKimProgrammer** [comment]
Reopened by mistake. Should have created a new issue.
