### ISSUE TITLE
Create Readme.md

### ISSUE THREAD

**Issue by TungKimProgrammer** [crex424/LibraryBookRegistration#12]
Create the Readme file for the project. It should have:
- [x] Badges
- [x] Add project Screen shots
- [x] Retouch grammar error and spelling and wording

**Comment by TungKimProgrammer** [comment]
I started the README.md with some minimum information.
Do you want to add some more to that?
If not, would you please close this issue?

**Comment by crex424** [comment]
I believe the last thing we need for the README is some screen shots of our project at work. Once that is done, we can close this issue.
