### ISSUE TITLE
Create CustomerDB Class

### ISSUE THREAD

**Issue by crex424** [crex424/LibraryBookRegistration#6]
Create CustomerDB class with:
Methods:
- [x] Add method with Customer parameter
- [x] Update method with Customer parameter that updates the database
- [x] Delete method with Customer parameter that deletes customer from database
- [x] Delete method with CustomerID parameter that deletes customer from database using their ID
- [x] GetCustomer method with CustomerID parameter. Returns a customer
- [x] GetAllCustomers method. Returns a List of customers

Pre-requisite: #5

**Comment by TungKimProgrammer** [comment]
Please correct if I am wrong:
- I thought the DBHelper Class should have methods to support working with the database such as SQLconnection, open and close connections or something similar.
- The CRUD methods should be in the StudentDB class or BookDB class or RegistrationDB class

**Comment by TungKimProgrammer** [comment]
Oh my mistake. It's just the name of the issue shot be changed.
Sorry and Thank you Campbell for doing great job

**Comment by crex424** [comment]
I believe the name is CustomerDB. I must have gotten mixed up while writing this issue. Thanks for the heads up.

**Comment by crex424** [comment]
That is true I believe, let me correct that real quick.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows

**Comment by TungKimProgrammer** [comment]
I have accepted the invitation so I am a collaborator now. I am able to edit the issues as you are. This is amazing. It's my pleasure working with you Campbell.

**Comment by crex424** [comment]
Same here. I did not know how to make the individual task into something that could be tracked. Great work with finding that out and editing the issues. Its also my please working with you Tung,


Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows

**Comment by TungKimProgrammer** [comment]
You are such a fast responder.
I was watching Joe's CPW 219 lecture, he's talking about checkboxes so I applied it right away. Cool feature.
On the right side of this Issue page, there's a link under Development: Create a branch for this issue or link a pull request.
It will create a branch for this issue with the issue number as prefix of branch name.
I think we could create a branch we are ready to assign the issue to you or me or both.
I didn't realize there are many steps finishing a small project like this until I planned it out.
The issues we created are just the small beginning part.

**Comment by crex424** [comment]
It really does seem simple until you actually plan it out.

**Comment by TungKimProgrammer** [comment]
Hi mate,
I currently have couple issues opening and pending because they requires something from your end:
- For my RegistrationDB, it needs my Registration class to be done first.
- For my Registration class \ ToString() to display Customer's Full Name + BookDB.GetBook(ISBN).Title + Registration Date: it needs CustomerDB.GetCustomer(CustomerID) method.

So basically all I need is the CustomerDB class. Thank you very much!

**Comment by crex424** [comment]
Hello @TungKimProgrammer,
I will hopefully have this class finished today. Sorry for taking so long to respond.
